[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C",
  "link-arg=-nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
]
runner = "probe-rs run --chip STM32F767ZITx"

[env]
DEFMT_LOG = "info"
DEFMT_RTT_BUFFER_SIZE = "4096"

[alias]
xtask = "run --package xtask --"
