[package]
name = "nucleo-f767zi"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { version = "0.10.0", features = [
  "platform-cortex-m",
  "executor-thread",
  "executor-interrupt",
  "defmt",
] }
embassy-time = { version = "0.5.1", features = ["tick-hz-32_768"] }
embassy-stm32 = { version = "0.6.0", features = [
  "stm32f767zi",
  "time-driver-any",
  "exti",
  "memory-x",
  "exti",
  "single-bank",
] }
embassy-sync = "0.8.0"
embassy-futures = "0.1.2"

defmt = "1.1.0"
defmt-rtt = "1.2.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

cortex-m = { version = "0.7.7", features = [
  "inline-asm",
  "critical-section-single-core",
] }
cortex-m-rt = "0.7.5"

[profile.release]
debug = 2
lto = true
opt-level = "s"
